extern const GeoLayout joon_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt1[];
extern const GeoLayout joon_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt2[];
extern const GeoLayout joon_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt3[];
extern const GeoLayout joon_Capless_Head[];
extern const GeoLayout joon_Left_Hand_Open[];
extern const GeoLayout joon_Right_Hand_Open[];
extern const GeoLayout joon_Right_Hand_Peace[];
extern const GeoLayout joon_Right_Hand_Cap[];
extern const GeoLayout joon_Right_Hand_Wing_Cap[];
extern const GeoLayout joon_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt1[];
extern const GeoLayout joon_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt2[];
extern const GeoLayout joon_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt3[];
extern const GeoLayout joon_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_joon_Capless_Head[];
extern const GeoLayout joon_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_joon_Left_Hand_Open[];
extern const GeoLayout joon_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_joon_Right_Hand_Open[];
extern const GeoLayout joon_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_joon_Right_Hand_Peace[];
extern const GeoLayout joon_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_joon_Right_Hand_Cap[];
extern const GeoLayout joon_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_joon_Right_Hand_Wing_Cap[];
extern const GeoLayout joon_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt1[];
extern const GeoLayout joon_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt2[];
extern const GeoLayout joon_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt3[];
extern const GeoLayout joon_2_LoD_Switch_opt0_Cap_State_Switch_opt1[];
extern const GeoLayout joon_2_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_joon_Capless_Head[];
extern const GeoLayout joon_2_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_joon_Left_Hand_Open[];
extern const GeoLayout joon_2_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_joon_Right_Hand_Open[];
extern const GeoLayout joon_2_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_joon_Right_Hand_Peace[];
extern const GeoLayout joon_2_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_joon_Right_Hand_Cap[];
extern const GeoLayout joon_2_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_joon_Right_Hand_Wing_Cap[];
extern const GeoLayout joon_2_LoD_Switch_opt0_Cap_State_Switch_opt2[];
extern const GeoLayout joon_2_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_joon_Capless_Head[];
extern const GeoLayout joon_2_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_joon_Left_Hand_Open[];
extern const GeoLayout joon_2_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_joon_Right_Hand_Open[];
extern const GeoLayout joon_2_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_joon_Right_Hand_Peace[];
extern const GeoLayout joon_2_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_joon_Right_Hand_Cap[];
extern const GeoLayout joon_2_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_joon_Right_Hand_Wing_Cap[];
extern const GeoLayout joon_2_LoD_Switch_opt0_Cap_State_Switch_opt3[];
extern const GeoLayout joon_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt1[];
extern const GeoLayout joon_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt2[];
extern const GeoLayout joon_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt3[];
extern const GeoLayout joon_geo[];
extern Lights1 joon_details_lights;
extern Lights1 joon_white_lights;
extern Lights1 joon_red_lights;
extern Lights1 joon_frills_lights;
extern Lights1 joon_Metal__METAL__lights;
extern Lights1 joon_details_ds_lights;
extern Lights1 joon_white_ds_lights;
extern Lights1 joon_hat_lights;
extern Lights1 joon_face_lights;
extern Lights1 joon_gold_lights;
extern Lights1 joon_brooch_lights;
extern Lights1 joon_glasses_lights;
extern Lights1 joon_hair_lights;
extern Lights1 joon_half_lights;
extern Lights1 joon_closed_lights;
extern Lights1 joon_dead_lights;
extern Lights1 joon_boots_dark_lights;
extern Lights1 joon_boots_light_lights;
extern u8 joon_details_ci8[];
extern u8 joon_details_pal_rgba16[];
extern u8 joon_frills_ci4[];
extern u8 joon_frills_pal_rgba16[];
extern u8 joon_Metal_Shade_rgba16_rgba16[];
extern u8 joon_Metal_Light_rgba16_rgba16[];
extern u8 joon_face_ci4[];
extern u8 joon_face_pal_rgba16[];
extern u8 joon_glasses_ci4[];
extern u8 joon_glasses_pal_rgba16[];
extern u8 joon_half_ci4[];
extern u8 joon_half_pal_rgba16[];
extern u8 joon_closed_ci4[];
extern u8 joon_closed_pal_rgba16[];
extern u8 joon_dead_ci4[];
extern u8 joon_dead_pal_rgba16[];
extern u8 joon_wing_2_ia8[];
extern u8 joon_wing1_ia8[];
extern Vtx joon_Butt_mesh_layer_1_vtx_0[58];
extern Gfx joon_Butt_mesh_layer_1_tri_0[];
extern Vtx joon_Butt_mesh_layer_1_vtx_1[63];
extern Gfx joon_Butt_mesh_layer_1_tri_1[];
extern Vtx joon_Butt_mesh_layer_1_vtx_2[22];
extern Gfx joon_Butt_mesh_layer_1_tri_2[];
extern Vtx joon_Butt_mesh_layer_4_vtx_0[20];
extern Gfx joon_Butt_mesh_layer_4_tri_0[];
extern Vtx joon_Torso_mesh_layer_1_vtx_0[44];
extern Gfx joon_Torso_mesh_layer_1_tri_0[];
extern Vtx joon_Torso_mesh_layer_1_vtx_1[61];
extern Gfx joon_Torso_mesh_layer_1_tri_1[];
extern Vtx joon_Torso_mesh_layer_1_vtx_2[22];
extern Gfx joon_Torso_mesh_layer_1_tri_2[];
extern Vtx joon_Torso_mesh_layer_1_vtx_3[10];
extern Gfx joon_Torso_mesh_layer_1_tri_3[];
extern Vtx joon_Torso_mesh_layer_1_vtx_4[9];
extern Gfx joon_Torso_mesh_layer_1_tri_4[];
extern Vtx joon_Torso_mesh_layer_1_vtx_5[12];
extern Gfx joon_Torso_mesh_layer_1_tri_5[];
extern Vtx joon_Torso_mesh_layer_1_vtx_6[5];
extern Gfx joon_Torso_mesh_layer_1_tri_6[];
extern Vtx joon_Torso_mesh_layer_1_vtx_7[8];
extern Gfx joon_Torso_mesh_layer_1_tri_7[];
extern Vtx joon_Torso_mesh_layer_4_vtx_0[4];
extern Gfx joon_Torso_mesh_layer_4_tri_0[];
extern Vtx joon_Torso_mesh_layer_4_vtx_1[20];
extern Gfx joon_Torso_mesh_layer_4_tri_1[];
extern Vtx joon_Head_DL_mesh_layer_4_vtx_0[16];
extern Gfx joon_Head_DL_mesh_layer_4_tri_0[];
extern Vtx joon_Head_DL_mesh_layer_4_vtx_1[26];
extern Gfx joon_Head_DL_mesh_layer_4_tri_1[];
extern Vtx joon_Head_DL_mesh_layer_1_vtx_0[87];
extern Gfx joon_Head_DL_mesh_layer_1_tri_0[];
extern Vtx joon_Head_DL_mesh_layer_1_vtx_1[26];
extern Gfx joon_Head_DL_mesh_layer_1_tri_1[];
extern Vtx joon_Head_DL_mesh_layer_1_vtx_2[397];
extern Gfx joon_Head_DL_mesh_layer_1_tri_2[];
extern Vtx joon_Head_DL_mesh_layer_1_vtx_3[88];
extern Gfx joon_Head_DL_mesh_layer_1_tri_3[];
extern Vtx joon_Head_DL_mesh_layer_1_vtx_4[26];
extern Gfx joon_Head_DL_mesh_layer_1_tri_4[];
extern Vtx joon_Head_DL_mesh_layer_1_vtx_5[28];
extern Gfx joon_Head_DL_mesh_layer_1_tri_5[];
extern Vtx joon_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_vtx_0[16];
extern Gfx joon_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_tri_0[];
extern Vtx joon_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_vtx_1[26];
extern Gfx joon_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_tri_1[];
extern Vtx joon_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_vtx_0[87];
extern Gfx joon_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_tri_0[];
extern Vtx joon_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_vtx_1[26];
extern Gfx joon_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_tri_1[];
extern Vtx joon_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_vtx_2[397];
extern Gfx joon_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_tri_2[];
extern Vtx joon_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_vtx_3[88];
extern Gfx joon_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_tri_3[];
extern Vtx joon_Left_Wing_DL_mesh_layer_4_vtx_0[4];
extern Gfx joon_Left_Wing_DL_mesh_layer_4_tri_0[];
extern Vtx joon_Left_Wing_DL_mesh_layer_4_vtx_1[4];
extern Gfx joon_Left_Wing_DL_mesh_layer_4_tri_1[];
extern Vtx joon_Right_Wing_DL_mesh_layer_4_vtx_0[4];
extern Gfx joon_Right_Wing_DL_mesh_layer_4_tri_0[];
extern Vtx joon_Right_Wing_DL_mesh_layer_4_vtx_1[4];
extern Gfx joon_Right_Wing_DL_mesh_layer_4_tri_1[];
extern Vtx joon_Left_Arm_Color_mesh_layer_1_vtx_0[36];
extern Gfx joon_Left_Arm_Color_mesh_layer_1_tri_0[];
extern Vtx joon_Left_Forearm_mesh_layer_1_vtx_0[20];
extern Gfx joon_Left_Forearm_mesh_layer_1_tri_0[];
extern Vtx joon_Left_Forearm_mesh_layer_1_vtx_1[26];
extern Gfx joon_Left_Forearm_mesh_layer_1_tri_1[];
extern Vtx joon_Left_Hand_DL_mesh_layer_1_vtx_0[51];
extern Gfx joon_Left_Hand_DL_mesh_layer_1_tri_0[];
extern Vtx joon_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1_vtx_0[50];
extern Gfx joon_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1_tri_0[];
extern Vtx joon_Right_Arm_Color_mesh_layer_1_vtx_0[36];
extern Gfx joon_Right_Arm_Color_mesh_layer_1_tri_0[];
extern Vtx joon_Right_Forearm_mesh_layer_1_vtx_0[20];
extern Gfx joon_Right_Forearm_mesh_layer_1_tri_0[];
extern Vtx joon_Right_Forearm_mesh_layer_1_vtx_1[26];
extern Gfx joon_Right_Forearm_mesh_layer_1_tri_1[];
extern Vtx joon_Right_Hand_DL_mesh_layer_1_vtx_0[52];
extern Gfx joon_Right_Hand_DL_mesh_layer_1_tri_0[];
extern Vtx joon_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1_vtx_0[52];
extern Gfx joon_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1_tri_0[];
extern Vtx joon_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1_vtx_0[70];
extern Gfx joon_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1_tri_0[];
extern Vtx joon_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1_vtx_0[50];
extern Gfx joon_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1_tri_0[];
extern Vtx joon_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1_vtx_1[26];
extern Gfx joon_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1_tri_1[];
extern Vtx joon_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1_vtx_2[28];
extern Gfx joon_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1_tri_2[];
extern Vtx joon_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1_vtx_0[50];
extern Gfx joon_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1_tri_0[];
extern Vtx joon_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1_vtx_1[26];
extern Gfx joon_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1_tri_1[];
extern Vtx joon_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1_vtx_2[28];
extern Gfx joon_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1_tri_2[];
extern Vtx joon_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4_vtx_0[8];
extern Gfx joon_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4_tri_0[];
extern Vtx joon_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4_vtx_1[8];
extern Gfx joon_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4_tri_1[];
extern Vtx joon_Left_Thigh_Color_mesh_layer_1_vtx_0[14];
extern Gfx joon_Left_Thigh_Color_mesh_layer_1_tri_0[];
extern Vtx joon_Left_Thigh_Color_mesh_layer_1_vtx_1[9];
extern Gfx joon_Left_Thigh_Color_mesh_layer_1_tri_1[];
extern Vtx joon_Left_Leg_mesh_layer_1_vtx_0[24];
extern Gfx joon_Left_Leg_mesh_layer_1_tri_0[];
extern Vtx joon_Left_Leg_mesh_layer_1_vtx_1[14];
extern Gfx joon_Left_Leg_mesh_layer_1_tri_1[];
extern Vtx joon_Left_Shoe_mesh_layer_1_vtx_0[32];
extern Gfx joon_Left_Shoe_mesh_layer_1_tri_0[];
extern Vtx joon_Left_Shoe_mesh_layer_1_vtx_1[8];
extern Gfx joon_Left_Shoe_mesh_layer_1_tri_1[];
extern Vtx joon_Right_Thigh_Color_mesh_layer_1_vtx_0[14];
extern Gfx joon_Right_Thigh_Color_mesh_layer_1_tri_0[];
extern Vtx joon_Right_Thigh_Color_mesh_layer_1_vtx_1[9];
extern Gfx joon_Right_Thigh_Color_mesh_layer_1_tri_1[];
extern Vtx joon_Right_Leg_mesh_layer_1_vtx_0[24];
extern Gfx joon_Right_Leg_mesh_layer_1_tri_0[];
extern Vtx joon_Right_Leg_mesh_layer_1_vtx_1[14];
extern Gfx joon_Right_Leg_mesh_layer_1_tri_1[];
extern Vtx joon_Right_Shoe_DL_mesh_layer_1_vtx_0[32];
extern Gfx joon_Right_Shoe_DL_mesh_layer_1_tri_0[];
extern Vtx joon_Right_Shoe_DL_mesh_layer_1_vtx_1[8];
extern Gfx joon_Right_Shoe_DL_mesh_layer_1_tri_1[];
extern Gfx mat_joon_details[];
extern Gfx mat_revert_joon_details[];
extern Gfx mat_joon_white[];
extern Gfx mat_joon_red[];
extern Gfx mat_joon_frills[];
extern Gfx mat_revert_joon_frills[];
extern Gfx mat_joon_Metal__METAL_[];
extern Gfx mat_revert_joon_Metal__METAL_[];
extern Gfx mat_joon_details_ds[];
extern Gfx mat_revert_joon_details_ds[];
extern Gfx mat_joon_white_ds[];
extern Gfx mat_joon_hat[];
extern Gfx mat_joon_face[];
extern Gfx mat_revert_joon_face[];
extern Gfx mat_joon_gold[];
extern Gfx mat_joon_brooch[];
extern Gfx mat_joon_glasses[];
extern Gfx mat_revert_joon_glasses[];
extern Gfx mat_joon_hair[];
extern Gfx mat_joon_half[];
extern Gfx mat_revert_joon_half[];
extern Gfx mat_joon_closed[];
extern Gfx mat_revert_joon_closed[];
extern Gfx mat_joon_dead[];
extern Gfx mat_revert_joon_dead[];
extern Gfx mat_joon_Wing_Tip[];
extern Gfx mat_revert_joon_Wing_Tip[];
extern Gfx mat_joon_Wing_Base[];
extern Gfx mat_revert_joon_Wing_Base[];
extern Gfx mat_joon_boots_dark[];
extern Gfx mat_joon_boots_light[];
extern Gfx joon_Butt_mesh_layer_1[];
extern Gfx joon_Butt_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx joon_Butt_mesh_layer_4[];
extern Gfx joon_Butt_mesh_layer_4_mat_override_Metal__METAL__0[];
extern Gfx joon_Torso_mesh_layer_1[];
extern Gfx joon_Torso_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx joon_Torso_mesh_layer_4[];
extern Gfx joon_Torso_mesh_layer_4_mat_override_Metal__METAL__0[];
extern Gfx joon_Head_DL_mesh_layer_4[];
extern Gfx joon_Head_DL_mesh_layer_4_mat_override_Metal__METAL__0[];
extern Gfx joon_Head_DL_mesh_layer_4_mat_override_half_1[];
extern Gfx joon_Head_DL_mesh_layer_4_mat_override_closed_2[];
extern Gfx joon_Head_DL_mesh_layer_4_mat_override_dead_3[];
extern Gfx joon_Head_DL_mesh_layer_1[];
extern Gfx joon_Head_DL_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx joon_Head_DL_mesh_layer_1_mat_override_half_1[];
extern Gfx joon_Head_DL_mesh_layer_1_mat_override_closed_2[];
extern Gfx joon_Head_DL_mesh_layer_1_mat_override_dead_3[];
extern Gfx joon_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4[];
extern Gfx joon_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_mat_override_Metal__METAL__0[];
extern Gfx joon_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_mat_override_half_1[];
extern Gfx joon_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_mat_override_closed_2[];
extern Gfx joon_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_mat_override_dead_3[];
extern Gfx joon_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1[];
extern Gfx joon_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx joon_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_half_1[];
extern Gfx joon_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_closed_2[];
extern Gfx joon_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_dead_3[];
extern Gfx joon_Left_Wing_DL_mesh_layer_4[];
extern Gfx joon_Left_Wing_DL_mesh_layer_4_mat_override_Metal__METAL__0[];
extern Gfx joon_Right_Wing_DL_mesh_layer_4[];
extern Gfx joon_Right_Wing_DL_mesh_layer_4_mat_override_Metal__METAL__0[];
extern Gfx joon_Left_Arm_Color_mesh_layer_1[];
extern Gfx joon_Left_Arm_Color_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx joon_Left_Forearm_mesh_layer_1[];
extern Gfx joon_Left_Forearm_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx joon_Left_Hand_DL_mesh_layer_1[];
extern Gfx joon_Left_Hand_DL_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx joon_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1[];
extern Gfx joon_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx joon_Right_Arm_Color_mesh_layer_1[];
extern Gfx joon_Right_Arm_Color_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx joon_Right_Forearm_mesh_layer_1[];
extern Gfx joon_Right_Forearm_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx joon_Right_Hand_DL_mesh_layer_1[];
extern Gfx joon_Right_Hand_DL_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx joon_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1[];
extern Gfx joon_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx joon_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1[];
extern Gfx joon_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx joon_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1[];
extern Gfx joon_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx joon_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1[];
extern Gfx joon_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx joon_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4[];
extern Gfx joon_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4_mat_override_Metal__METAL__0[];
extern Gfx joon_Left_Thigh_Color_mesh_layer_1[];
extern Gfx joon_Left_Thigh_Color_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx joon_Left_Leg_mesh_layer_1[];
extern Gfx joon_Left_Leg_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx joon_Left_Shoe_mesh_layer_1[];
extern Gfx joon_Left_Shoe_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx joon_Right_Thigh_Color_mesh_layer_1[];
extern Gfx joon_Right_Thigh_Color_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx joon_Right_Leg_mesh_layer_1[];
extern Gfx joon_Right_Leg_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx joon_Right_Shoe_DL_mesh_layer_1[];
extern Gfx joon_Right_Shoe_DL_mesh_layer_1_mat_override_Metal__METAL__0[];
